[package]
name = "client"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
piston_window = "0.55.0"
clock_ticks = "*"
glutin = "0.6.2"
shared = { path = "../shared", version = "0.1.0" }
server = { path = "../server", version = "0.1.0", optional = true }
netsync = { path = "../deps/netsync", version = "0.1.0" }
hexahydrate = { path = "../deps/hexahydrate", version = "0.1.0" }
cobalt = { git = "https://github.com/bonsaiden/cobalt-rs.git", rev = "server_stream" }
clap = "*"
clippy = { version = "*", optional = true }

[features]
loopback = ["server"]
default = ["loopback"]
lint = ["clippy"]

